### PR TITLE
Add S4 support

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
This creates a module file for S4 so Fit2Obs can be built on that system.

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
@jack-woollen I am currently testing this installation on S4 and I will send along test fits data when complete, which should be in a couple hours or so.

**Comment by DavidHuber-NOAA** [comment]
@jack-woollen I have finished my test run on S4.  Would you kindly check out the data?  I have placed it on Hera: `/scratch1/NESDIS/nesdis-rdo2/David.Huber/for_jack/{fits,horiz}`.  Thanks!

**Comment by DavidHuber-NOAA** [comment]
@jack-woollen I should mention that this experiment was run out 7 days with GFS forecasts performed once per day out to 144 hours.

**Comment by jack-woollen** [comment]
@DavidHuber-NOAA The fits look okay. They were run for days 1 thru 5.

**Comment by DavidHuber-NOAA** [comment]
@jack-woollen Apologies.  I seem to have sent over an earlier tarball.  I have updated the contents to include day 6.  Would you mind taking another look?  Thanks!

**Comment by jack-woollen** [comment]
@DavidHuber-NOAA Now all there for days 1-6.

**Comment by DavidHuber-NOAA** [comment]
Great, thank you!  Could we go ahead with the review then?  BTW, I don't need a new tag for this since S4 is a tier 2 machine.

**Comment by DavidHuber-NOAA** [comment]
@jack-woollen I just discovered this is still open.  Could we go ahead and merge this?

**Review by jack-woollen — APPROVED** [review]

**Comment by jack-woollen** [comment]
@DavidHuber-NOAA Sorry for the LONG delay!

**Comment by DavidHuber-NOAA** [comment]
Hehe no problem.

**Pull request merged**
