### PR TITLE
Build fit2obs w/ cmake.

### LINKED ISSUE #6: Build fit2obs w/ cmake
As the GFS application is cmake compatible, fit2obs will need to be updated to be built w/ cmake.
I will use this issue to document the progress for that work.

@KateFriedman-NOAA @jack-woollen FYI.

### PR DESCRIPTION
**Pull request by aerorahul**
Fixes #6

Usage:
```bash
./ush/build.sh
```

### CODE REVIEW

**Review by WalterKolczynski-NOAA — APPROVED** [review]

**Review by KateFriedman-NOAA — APPROVED** [review]
Tested build on Hera, Orion, and both WCOSS2s. Builds without issue. I can fold exec name (add `.x`) and location change (`exec` -> `install/exec`) into my branch/PR.

**Comment by aerorahul** [comment]
Thank you @KateFriedman-NOAA @WalterKolczynski-NOAA 
Will wait for @jack-woollen to review, approve and may be merge.

**Review by jack-woollen — APPROVED** [review]

**Comment by jack-woollen** [comment]
@KateFriedman-NOAA @aerorahul  I'm presuming the update is now complete, and I can make a tag. Also, a very dumb question. how do I cmake the executables?

**Comment by aerorahul** [comment]
> @KateFriedman-NOAA @aerorahul  I'm presuming the update is now complete, and I can make a tag. Also, a very dumb question. how do I cmake the executables?

Not sure what you mean? The executables are placed in install/exec. They can be moved if you wish to bring them out to root_dir/exec.

**Comment by jack-woollen** [comment]
@aerorahul  Let's say I just cloned Fit2Obs from github. How to run cmake?

**Comment by aerorahul** [comment]
> @aerorahul  Let's say I just cloned Fit2Obs from github. How to run cmake? 

I see. 
Just execute:
./ush/build.sh

**Comment by KateFriedman-NOAA** [comment]
> I'm presuming the update is now complete, and I can make a tag.

@jack-woollen I have another branch with script updates and @DavidHuber-NOAA will have updates to build on Jet. I also have a global-workflow branch with updates to run fit2obs in a separate job instead of within another one (as it has been running). I'm checking on my WCOSS2 test today and plan to hopefully send you output and logs to check for both Orion and WCOSS2. Once my fit2obs branch and Jet updates get in we'd love a new tag. Thanks!

**Comment by jack-woollen** [comment]
@KateFriedman-NOAA  The cmake process adds a .x to the exec names and puts them in the install directory. I made some changes to restore them to their original names and locations so none of the other ush  scripts need to compensate for that.

**Comment by KateFriedman-NOAA** [comment]
@jack-woollen Ok. I had updated the scripts in my fit2obs branch to account for the new names and locations but I can revert those changes once you commit your changes to the fit2obs `develop` branch. Let me know, thanks!

**Comment by jack-woollen** [comment]
@KateFriedman-NOAA  Done!

**Comment by aerorahul** [comment]
@jack-woollen 
Apologies for the radio silence. I was on leave last week.

The objective of turning `fit2obs` into a `cmake` project does not stop at just building with `cmake`.  We would like to be able to build and install `fit2obs` as a package that can be loaded via `module load`.  This is what we do in `obsproc` and `prepobs`. 

I will open a follow-up issue outlining exactly what that will mean.

Adding `.x` to the executables is also part of the standardization we are performing as part of the GFS upgrades. 

I am happy to provide any further information you may have questions for.

Thanks~

**Pull request merged**
