### PR TITLE
Migrate to spack-stack; add Hercules support.

### LINKED ISSUE #15: Add Hercules support
The new MSU partition Hercules has come online. Add support for Hercules.

See https://github.com/NOAA-EMC/global-workflow/issues/1588 for more details.

### PR DESCRIPTION
**Pull request by DavidHuber-NOAA**
This upgrades the module files for each R&D system to point to the spack-stack libraries and adds support for Hercules.  The WCOSS2 modules no longer load fit2obs_common since module names and versions differ slightly from the R&D systems.  Lastly, references to Cheyenne have been removed as that system was decommissioned.

So far, testing has been performed on Hercules by running two experiments and comparing the results.  The first experiment used the Orion-built executables with Intel version 18 compilers.  The second case used the builds from this branch.  The results were bitwise identical for all Fit2Obs output files out to 120 hours.  The outputs can be found in the following directories, respectively:

```console
/work/noaa/global/dhuber/archive/herc_old_f2o/{fits,horiz}
/work/noaa/global/dhuber/archive/herc_new_f2o/{fits,horiz}
```

<strike> A similar test will be performed on WCOSS2. </strike> Shorter tests (out to 2 days) will be performed on Orion and Hera and build-only tests will be performed on _WCOSS2_, Jet, and S4.

- [x] Hercules
- [x] WCOSS2
- [x] Hera
- [x] Orion
- [x] Jet
- [x] S4

Resolves #15 #16

### CODE REVIEW

**Comment by DavidHuber-NOAA** [comment]
This isn't yet testable in the global workflow on WCOSS2 as the library versions have not been updated yet.  I will convert this PR to only affect the R&D machines for now and update the branch when the global workflow is ready to upgrade WCOSS2 libraries across all submodules.

**Comment by DavidHuber-NOAA** [comment]
All tests were successful on all systems: 48-cycle test on Hercules, 12-cycle tests on Hera and Orion, and build tests on Jet, S4, and WCOSS2.  Marking 'ready for review'.  Would you be able to review this @jack-woollen?

**Review by jack-woollen — APPROVED** [review]

**Comment by jack-woollen** [comment]
@DavidHuber-NOAA Done.

**Comment by DavidHuber-NOAA** [comment]
Thanks @jack-woollen!

**Pull request merged**
